// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/menu": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "添加菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "菜单数据",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.menuForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"msg\":\"添加成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/menu/:menu_id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "获取菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":menu,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "修改菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " 菜单数据",
                        "name": "menu",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.menuForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"msg\":\"修改成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/menus": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "菜单列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":menus,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "菜单ID数组",
                        "name": "menu_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"删除成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"删除失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/path": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "接口管理"
                ],
                "summary": "添加接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "接口数据",
                        "name": "path",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.pathForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"msg\":\"添加成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/path/:path_id": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "接口管理"
                ],
                "summary": "获取接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":path,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "接口管理"
                ],
                "summary": "修改接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " 接口数据",
                        "name": "path",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.pathForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"msg\":\"修改成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/paths": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "接口管理"
                ],
                "summary": "接口列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":paths,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "接口管理"
                ],
                "summary": "删除接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "接口ID数组",
                        "name": "path_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"删除成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"删除失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/role": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "添加角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "角色数据",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.roleForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"msg\":\"添加成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/role/:role_id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "修改角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "角色数据",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.roleForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"msg\":\"修改成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/roles": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "获取角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":logs,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "日志ID数组",
                        "name": "role_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"删除成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"删除失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "添加用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "账号信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.userCreateForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"添加成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"添加失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/user/:user_id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "账号信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.userUpdateForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"修改成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"修改失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":info,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "账号密码",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.loginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":{token:\"token\"},\"msg\":\"登录成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/user/logs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取登录日志列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":logs,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除登录日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "日志ID数组",
                        "name": "userlogid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"删除成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"删除失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/user/pwd/:user_id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "账号密码信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.userUpdatePwdForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"修改成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"修改失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":logs,\"msg\":\"获取成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"msg\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "日志ID数组",
                        "name": "userlogid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":0,\"data\":null,\"msg\":\"删除成功\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"data\":null,\"msg\":\"删除失败\"}",
                        "schema": {
                            "$ref": "#/definitions/apis.Res"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apis.Res": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apis.loginForm": {
            "type": "object",
            "required": [
                "password",
                "user_name"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "apis.menuForm": {
            "type": "object",
            "required": [
                "component",
                "icon",
                "name",
                "path",
                "title",
                "type"
            ],
            "properties": {
                "component": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "hidden": {
                    "type": "integer"
                },
                "icon": {
                    "type": "string"
                },
                "menu_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "redirect": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "apis.pathForm": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "create_time": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "path_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "apis.roleForm": {
            "type": "object",
            "required": [
                "role_name"
            ],
            "properties": {
                "buttons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Button"
                    }
                },
                "create_time": {
                    "type": "string"
                },
                "menu_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "path_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "role_id": {
                    "type": "integer"
                },
                "role_name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "update_time": {
                    "type": "string"
                }
            }
        },
        "apis.userCreateForm": {
            "type": "object",
            "required": [
                "password",
                "repassword",
                "role_ids",
                "user_name"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "repassword": {
                    "type": "string"
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "apis.userUpdateForm": {
            "type": "object",
            "required": [
                "role_ids",
                "user_name"
            ],
            "properties": {
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "apis.userUpdatePwdForm": {
            "type": "object",
            "required": [
                "old_password",
                "password",
                "repassword"
            ],
            "properties": {
                "old_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "repassword": {
                    "type": "string"
                }
            }
        },
        "models.Button": {
            "type": "object",
            "properties": {
                "btns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "menu_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "127.0.0.1:8001",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Go-Admin-Element",
	Description: "Go-Admin-Element后端API文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
