application:
  env: dev
  host: 127.0.0.1
  isinit: false
  jwtsecret: go-vue.usenav.com
  name: go-element-admin-api
  port: 8001
database:
  database: go-element-admin
  dbtype: mysql
  host: 127.0.0.1
  password: 12345678
  port: 3306
  username: root
